{% set name = "pybind11_json" %}
{% set version = "0.2.8" %}
{% set sha256 = "fcce424d238c52f2f12a7c5163e8ae07b221388f936d6c5b513d99de7d8fcfee" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pybind/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - cmake
    - ninja  # [win]
    - make   # [unix]
  host:
    - python
    - pybind11 >=2.2.4,<3.0
    - nlohmann_json >=3.2.0,<4.0
  run:
    - python

test:
  commands:
    - test -d ${PREFIX}/include/pybind11_json                                                    # [unix]
    - test -f ${PREFIX}/include/pybind11_json/pybind11_json.hpp                                  # [unix]
    - test -f ${PREFIX}/share/cmake/pybind11_json/pybind11_jsonConfig.cmake                      # [unix]
    - test -f ${PREFIX}/share/cmake/pybind11_json/pybind11_jsonConfigVersion.cmake               # [unix]
    - if not exist %LIBRARY_INC%\pybind11_json\pybind11_json.hpp (exit 1)                        # [win]
    - if not %LIBRARY_LIB%\cmake\pybind11_json\pybind11_jsonConfig.cmake (exit 1)                # [win]
    - if not %LIBRARY_LIB%\cmake\pybind11_json\pybind11_jsonConfigVersion.cmake (exit 1)         # [win]

about:
  home: http://github.com/pybind/pybind11_json
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Using nlohmann::json with pybind11

  description: |
    pybind11_json is an nlohmann::json to pybind11 bridge, it allows you to
    automatically convert nlohmann::json to py::object and the other way around.
  dev_url: https://github.com/pybind/pybind11_json

extra:
  recipe-maintainers:
    - SylvainCorlay
    - JohanMabille
    - martinRenou
    - wjakob
